name: Update newsletter
on:
  schedule:
    - cron: '0 8 * * *' # runs at 08:00 UTC daily
  workflow_dispatch: # lets you click a button to test it manually

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Fetch email and generate HTML
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          ALLOWED_SENDERS: ${{ secrets.ALLOWED_SENDERS }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated newsletter update" && git push)